#!/bin/sh
# Strip everything specific to this build before the disk is packaged.
set -eux

pkg autoremove -y
pkg clean -ay
rm -rf /var/db/freebsd-update/*
# Distribution sets the installer downloaded (see installerconfig).
rm -rf /usr/freebsd-dist

# Regenerated by rc.d/sshd on first boot, so every VM gets its own.
rm -f /etc/ssh/ssh_host_*
# Rewritten by dhclient on first boot from the consumer's network.
rm -f /etc/resolv.conf /var/db/dhclient.leases.*

rm -f /root/.history /home/vagrant/.history /home/vagrant/.sh_history
find /var/log -type f -exec truncate -s 0 {} +
rm -rf /tmp/* /var/tmp/*

# Zero free space so the qcow2 compresses. dd stops with ENOSPC, by design.
dd if=/dev/zero of=/zero bs=1m || true
rm -f /zero
sync
